PLMVC/Controllers/DiscoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PLMVC.Controllers
{
    public class DiscoController : Controller
    {
        // GET: Disco
        public ActionResult GetAll()
        {
            ML.Result result = BL.Disco.GetAll();
            ML.Disco disco = new ML.Disco();
            disco.Discos = new List<object>();
            if (result.Correct)
            {
                disco.Discos = result.Objects;
            }
            else
            {
                ViewBag.Message = result.ErrorMessage;

            }
            return View(disco);
        }
        [HttpGet]
        public ActionResult Form(int? IdDisco)
        {

            ML.Disco disco = new ML.Disco();
            //ML.Disco disco=new ML.Disco();
            


            if (IdDisco != null)//Update
            {
                //ML.Result result=new ML.Result();
                ML.Result result = BL.Disco.GetById(IdDisco.Value);
                if (result.Correct)
                {
                    disco = (ML.Disco)result.Object;
                   
                }
            }
           
            return View(disco);
            //return View(disco1);

        }
        [HttpPost]
        public ActionResult Form(ML.Disco disco)
        {
            //ML.Result result = new ML.Result();
            if (disco.IdDisco == 0)//Add
            {
                ML.Result result = BL.Disco.Add(disco);
                if (result.Correct)
                {
                    ViewBag.Mensaje = "Se agrego correctamente";
                }
                else
                {
                    ViewBag.Mensaje = "No se pudo registrar el disco correctamente" + result.ErrorMessage;
                }
            }
            else//Update
            {
                ML.Result result = BL.Disco.Update(disco);
                if (result.Correct)
                {
                    ViewBag.Mensaje = "Actualizado Correctamente";
                }
                else
                {
                    ViewBag.Mensaje = "No se pudo registrar el disco" + result.ErrorMessage;
                }

            }
            return PartialView("Modal");
        }
        [HttpGet]
        public ActionResult Delete(int IdDisco)
        {
            ML.Result result = BL.Disco.DeleteEF(IdDisco);

            if (result.Correct)
            {
                ViewBag.Mensaje = "Eliminado correctamente";
            }
            else
            {
                ViewBag.Mensaje = "No se pudo eliminar correctamente " + result.ErrorMessage;
            }
            return PartialView("Modal");
        }
    }
}

PLMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PLMVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

PLMVC/Views/Disco/Form.cshtml
@model ML.Disco
@{
    ViewBag.Title = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Registrar Discos</h2>
<h5>Llena los campos para registrar el disco</h5>
<hr />
<div class="container">
    @using (Html.BeginForm("Form", "Disco", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <div class="row">
            @Html.HiddenFor(model => model.IdDisco)

            <div class="col-md-3">
                @Html.LabelFor(model => Model.Titulo)
                @Html.TextBoxFor(model => Model.Titulo, new { @class = "form-control" })
            </div>
            <div class="col-md-3">
                @Html.LabelFor(model => Model.Artista)
                @Html.TextBoxFor(model => Model.Artista, new { @class = "form-control" })

            </div>
            <div class="col-md-3">
                @Html.LabelFor(model => Model.GeneroMusical)
                @Html.TextBoxFor(model => Model.GeneroMusical, new { @class = "form-control" })
            </div>
            <div class="col-md-3">
                @Html.LabelFor(model => Model.Duracion)
                @Html.TextBoxFor(model => Model.Duracion, new { @class = "form-control" })
            </div>

        </div>
        <div class="row">
            <div class="col-md-3">
                @Html.LabelFor(model => Model.Año)
                @Html.TextBoxFor(model => Model.Año, new { @class = "form-control" })
            </div>
            <div class="col-md-3">
                @Html.LabelFor(model => Model.Distribuidora)
                @Html.TextBoxFor(model => Model.Distribuidora, new { @class = "form-control" })
            </div>
            <div class="col-md-3">
                @Html.LabelFor(model => Model.Ventas)
                @Html.TextBoxFor(model => Model.Ventas, new { @class = "form-control" })
            </div>
            <div class="col-md-3">
                @Html.LabelFor(model => Model.Disponibilidad)
                @Html.TextBoxFor(model => Model.Disponibilidad, new { @class = "form-control" })
            </div>
        </div>
   <br />
            <input class="btn btn-primary" type="submit" name="name" value="Guardar" />
            @Html.ActionLink("Cancelar", "GetAll", "Disco", htmlAttributes: new { @class = "btn btn-danger custom-button" })

    }
</div>

PLMVC/Views/Disco/GetAll.cshtml
@model ML.Disco
@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.css" />
@Scripts.Render("~/bundles/jquery")
<script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.js"></script>



<div class="text-center">
    <h2>GetAll</h2>
    <h1>Tabla de usuarios registrados</h1>
    <a class="btn btn-success btn-lg" href="@Url.Action("Form","Disco")"><i class="fa-solid fa-user-plus" style="color: black;"></i> Agregar</a>
   
</div>
<hr />

@if (Model.Discos != null)
{
    <!--Tabla-->
    <div class="table-responsive">
        <table class="table table-striped" id="tablaUsuario">
            <thead>
                <tr >

                    <th scope="col" class="text-center">Id Disco</th>
                    <th scope="col" class="text-center">Titulo</th>
                    <th scope="col" class="text-center">Artista</th>
                    <th scope="col" class="text-center">Genero Musical</th>
                    <th scope="col" class="text-center">Duracion</th>
                    <th scope="col" class="text-center">Año</th>
                    <th scope="col" class="text-center">Distribuidora</th>
                    <th scope="col" class="text-center">Ventas</th>
                    <th scope="col" class="text-center">Disponibilidad</th>
                    <th scope="col" class="text-center">Acciones</th>
                </tr>
            </thead>

            <tbody class="table-striped">
                @foreach (ML.Disco disco in Model.Discos)
                {
                    <tr>
                    
                        <td>@disco.IdDisco</td>
                        <td>@disco.Titulo</td>
                        <td>@disco.Artista</td>
                        <td>@disco.GeneroMusical</td>
                        <td>@disco.Duracion</td>
                        <td>@disco.Año</td>
                        <td>@disco.Distribuidora</td>
                        <td>@disco.Ventas</td>
                        <td>@disco.Disponibilidad</td>
                       
                        <td>
                            <a class="btn btn-danger  " href="@Url.Action("Delete", "Disco", new { IdDisco = disco.IdDisco})"><i class="fa-solid fa-trash"></i></a><br />
                            <a class="btn btn-warning " href="@Url.Action("Form", "Disco", new { IdDisco = disco.IdDisco })"><i class="fa-solid fa-pen"></i></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <!--Fin tabla-->
}
else
{
    <div class="alert alert-danger" role="alert">
        No se encontraron Usuarios registrados.Error:@ViewBag.Message
    </div>
}

PLMVC/Views/Disco/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="Modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Mensaje</h5>
            </div>
            <div class="modal-footer">
                @*@Html.ActionLink("Regresar", "GetAll", "Materia", htmlAttributes: new { @class = "btn btn-danger" })*@
                @Html.ActionLink("Continuar", "GetAll", "Disco", htmlAttributes: new { @class = "btn btn-danger" })


            </div>
        </div>
    </div>
</div>

<script>$('#Modal').modal();</script>

PLMVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

PLMVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

PLMVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

PLMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Discos", "GetAll", "Disco", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>